import { GOVERNANCE_DOC_PATHS } from './governanceDocPaths.js';

const createGovernanceAsset = ({
    id,
    kind,
    relativePath,
    producedBy,
    checkedBy = [],
    status = 'governed',
    sourceRefs = [],
}) => ({
    id,
    kind,
    path: relativePath,
    producedBy,
    checkedBy,
    status,
    sourceRefs,
});

export const buildGovernanceAssets = () => [
    createGovernanceAsset({
        id: 'dependency-sbom-snapshot',
        kind: 'dependency-sbom',
        relativePath: 'tools/governance/dependency-sbom.snapshot.json',
        producedBy: 'tools/scripts/check-sbom-governance.mjs',
        checkedBy: ['tools/scripts/check-dependency-governance.mjs'],
        sourceRefs: ['pnpm-lock.yaml', 'package.json'],
    }),
    createGovernanceAsset({
        id: 'dependency-license-allowlist',
        kind: 'license-allowlist',
        relativePath: 'tools/governance/dependency-license-allowlist.json',
        producedBy: 'tools/governance/dependency-license-allowlist.json',
        checkedBy: ['tools/scripts/check-license-governance.mjs'],
        sourceRefs: ['pnpm-lock.yaml'],
    }),
    createGovernanceAsset({
        id: 'dependency-runtime-governance-doc',
        kind: 'secret-policy',
        relativePath: GOVERNANCE_DOC_PATHS.dependencyRuntimeGovernance,
        producedBy: 'manual-governance-document',
        checkedBy: [
            'tools/scripts/check-dependency-governance.mjs',
            'tools/scripts/check-secret-governance.mjs',
        ],
        sourceRefs: ['apps/desktop/electron/runtimeConfig.js'],
    }),
    createGovernanceAsset({
        id: 'runtime-config-policy-source',
        kind: 'runtime-policy-source',
        relativePath: 'apps/desktop/electron/runtimeConfig.js',
        producedBy: 'apps/desktop/electron/runtimeConfig.js',
        checkedBy: [
            'tools/scripts/check-secret-governance.mjs',
            'tools/scripts/check-dependency-governance.mjs',
        ],
        sourceRefs: [GOVERNANCE_DOC_PATHS.dependencyRuntimeGovernance],
    }),
    createGovernanceAsset({
        id: 'runtime-drill-snapshot',
        kind: 'runtime-snapshot',
        relativePath: 'tools/governance/runtime-drill.snapshot.json',
        producedBy: 'tools/governance/runtime-drill.snapshot.json',
        checkedBy: ['tools/scripts/check-runtime-drill-governance.mjs'],
    }),
    createGovernanceAsset({
        id: 'desktop-policy-snapshot',
        kind: 'desktop-policy',
        relativePath: 'tools/governance/desktop-policy.snapshot.json',
        producedBy: 'tools/governance/desktop-policy.snapshot.json',
        checkedBy: ['tools/scripts/check-electron-governance.mjs'],
        sourceRefs: [
            'apps/desktop/electron/preloadContract.cjs',
            'apps/desktop/electron/desktopGovernance.js',
        ],
    }),
    createGovernanceAsset({
        id: 'release-health-operations-snapshot',
        kind: 'operations-snapshot',
        relativePath: 'tools/governance/release-health-operations.snapshot.json',
        producedBy: 'tools/governance/release-health-operations.snapshot.json',
        checkedBy: [
            'tools/scripts/releaseHealthOperations.js',
            'tools/scripts/export-governance-artifacts.mjs',
        ],
    }),
    createGovernanceAsset({
        id: 'release-artifact-evidence-script',
        kind: 'release-artifact-evidence',
        relativePath: 'tools/scripts/check-release-artifacts.mjs',
        producedBy: 'tools/scripts/check-release-artifacts.mjs',
        checkedBy: ['tools/scripts/__tests__/releaseArtifactEvidence.test.ts'],
        sourceRefs: [GOVERNANCE_DOC_PATHS.releaseHealthChecklist],
    }),
    createGovernanceAsset({
        id: 'boundary-registry-snapshot',
        kind: 'boundary-registry',
        relativePath: 'tools/governance/boundary-registry.snapshot.json',
        producedBy: 'tools/governance/boundary-registry.snapshot.json',
        checkedBy: ['tools/scripts/check-boundary-governance.mjs'],
    }),
    createGovernanceAsset({
        id: 'contract-registry-snapshot',
        kind: 'contract-registry',
        relativePath: 'tools/governance/contract-registry.snapshot.json',
        producedBy: 'tools/governance/contract-registry.snapshot.json',
        checkedBy: ['packages/shared/src/logic/__tests__/contractSnapshot.test.ts'],
        sourceRefs: ['packages/shared/src/logic/contractSnapshot.ts'],
    }),
    createGovernanceAsset({
        id: 'turn-credential-client-source',
        kind: 'turn-lifecycle-source',
        relativePath: 'apps/desktop/electron/turnCredentialClient.js',
        producedBy: 'apps/desktop/electron/turnCredentialClient.js',
        checkedBy: ['apps/desktop/electron/__tests__/turnCredentialClient.test.ts'],
        sourceRefs: [
            'packages/turn-service/src/turnCredentialService.js',
            'apps/desktop/src/app/runtime/useRuntimeAppConfig.ts',
        ],
    }),
    createGovernanceAsset({
        id: 'turn-credential-service-source',
        kind: 'turn-lifecycle-source',
        relativePath: 'packages/turn-service/src/turnCredentialService.js',
        producedBy: 'packages/turn-service/src/turnCredentialService.js',
        checkedBy: ['packages/turn-service/src/__tests__/turnCredentialService.test.ts'],
        sourceRefs: ['apps/desktop/electron/turnCredentialClient.js'],
    }),
    createGovernanceAsset({
        id: 'runtime-relay-loader-source',
        kind: 'turn-lifecycle-source',
        relativePath: 'apps/desktop/src/app/runtime/useRuntimeAppConfig.ts',
        producedBy: 'apps/desktop/src/app/runtime/useRuntimeAppConfig.ts',
        checkedBy: ['apps/desktop/src/app/runtime/__tests__/useRuntimeAppConfig.test.tsx'],
        sourceRefs: [
            'apps/desktop/electron/turnCredentialClient.js',
            'packages/shared/src/config/webrtc.ts',
        ],
    }),
    createGovernanceAsset({
        id: 'repo-settings-snapshot',
        kind: 'repo-settings-desired-state',
        relativePath: 'tools/governance/repo-settings.snapshot.json',
        producedBy: 'tools/governance/repo-settings.snapshot.json',
        checkedBy: ['tools/scripts/check-repo-settings-governance.mjs'],
        sourceRefs: [GOVERNANCE_DOC_PATHS.repoSettingsChecklist],
    }),
    createGovernanceAsset({
        id: 'codeowners-role-map-snapshot',
        kind: 'codeowners-role-map',
        relativePath: 'tools/governance/codeowners-role-map.snapshot.json',
        producedBy: 'tools/governance/codeowners-role-map.snapshot.json',
        checkedBy: ['tools/scripts/check-codeowners-governance.mjs'],
        sourceRefs: ['.github/CODEOWNERS', 'tools/governance/boundary-registry.snapshot.json'],
    }),
    createGovernanceAsset({
        id: 'release-changelog-snapshot',
        kind: 'release-changelog-coverage',
        relativePath: 'tools/governance/release-changelog.snapshot.json',
        producedBy: 'tools/governance/release-changelog.snapshot.json',
        checkedBy: ['tools/scripts/check-changelog-governance.mjs'],
        sourceRefs: ['CHANGELOG.md'],
    }),
    createGovernanceAsset({
        id: 'benchmark-baseline-snapshot',
        kind: 'benchmark-baseline',
        relativePath: 'tools/governance/benchmark-baselines.snapshot.json',
        producedBy: 'tools/governance/benchmark-baselines.snapshot.json',
        checkedBy: ['tools/scripts/run-lifecycle-benchmarks.mjs'],
    }),
    createGovernanceAsset({
        id: 'audit-gates-snapshot',
        kind: 'audit-gate-contract',
        relativePath: 'tools/governance/audit-gates.snapshot.json',
        producedBy: 'tools/governance/audit-gates.snapshot.json',
        checkedBy: ['tools/scripts/check-audit-gates.mjs'],
        sourceRefs: ['package.json', '.github/workflows/governance.yml'],
    }),
    createGovernanceAsset({
        id: 'lifecycle-dashboard-snapshot',
        kind: 'lifecycle-dashboard-contract',
        relativePath: 'tools/governance/lifecycle-dashboard.snapshot.json',
        producedBy: 'tools/governance/lifecycle-dashboard.snapshot.json',
        checkedBy: [
            'tools/scripts/generate-governance-report.mjs',
            'tools/scripts/check-lifecycle-certification.mjs',
        ],
        sourceRefs: ['tools/governance/audit-gates.snapshot.json'],
    }),
    createGovernanceAsset({
        id: 'lifecycle-certification-snapshot',
        kind: 'lifecycle-certification-contract',
        relativePath: 'tools/governance/lifecycle-certification.snapshot.json',
        producedBy: 'tools/governance/lifecycle-certification.snapshot.json',
        checkedBy: ['tools/scripts/check-lifecycle-certification.mjs'],
        sourceRefs: ['docs/archive/engineering-audit-report-2026-04-25.md'],
    }),
    createGovernanceAsset({
        id: 'seal-exclusions-review-snapshot',
        kind: 'seal-exclusion-review',
        relativePath: 'tools/governance/seal-exclusions-review.snapshot.json',
        producedBy: 'tools/governance/seal-exclusions-review.snapshot.json',
        checkedBy: ['tools/scripts/check-seal-exclusion-governance.mjs'],
        sourceRefs: ['packages/config-vitest/sealExclusions.js'],
    }),
];
