export const DESKTOP_STAGE_WIDTH_PX = 3840;
export const DESKTOP_ASPECT_16_9 = 16 / 9;
export const DESKTOP_STAGE_HEIGHT_PX = DESKTOP_STAGE_WIDTH_PX / DESKTOP_ASPECT_16_9;
export const DESKTOP_TOP_BAR_HEIGHT_PX = 120;
export const DESKTOP_ZONE_HEIGHT_PX = 520;
export const DESKTOP_CENTER_HEIGHT_PX =
    DESKTOP_STAGE_HEIGHT_PX - DESKTOP_TOP_BAR_HEIGHT_PX - DESKTOP_ZONE_HEIGHT_PX;
export const DESKTOP_SHELL_ARTWORK_HEIGHT_PX = DESKTOP_TOP_BAR_HEIGHT_PX + DESKTOP_CENTER_HEIGHT_PX;

export const DESKTOP_BOARD_SCALE_MIN = 1.2;
export const DESKTOP_BOARD_SCALE_MAX = 2.08;
export const DESKTOP_DECK_SCALE = 1.12;
export const DESKTOP_ZONE_SCALE = 1;
export const DESKTOP_MAIN_GAP_PX = 24;
